<a href="https://colab.research.google.com/github/Abhishek264/ml-bootcamp/blob/main/Day1_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=[1,2,3,4,5]

arr1=np.array(a)

b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(type(a))

<class 'list'>


In [ ]:
import numpy as np
s=np.arange(1000)
print("size of each elements of list in bytes",s.itemsize)

size of each elements of list in bytes 8


In [ ]:
import numpy as np
import time
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
arr_mul=arr1*arr2
end=time.time()
print("total time taken is",end-start)


total time taken is 0.00011086463928222656


In [2]:
import numpy as np
arr1=np.zeros((2,2))
print(arr1)

[[0. 0.]
 [0. 0.]]


In [3]:
import pandas as pd
web=pd.read_html("https://en.wikipedia.org/wiki/States_and_union_territories_of_India")[3]

In [4]:
web.head()

State  ... Additional officiallanguages[39]
0     Andhra Pradesh  ...                                —
1  Arunachal Pradesh  ...                                —
2              Assam  ...                    Bengali, Bodo
3              Bihar  ...                             Urdu
4       Chhattisgarh  ...                    Chhattisgarhi

[5 rows x 11 columns]

In [5]:
excel=pd.read_excel("/content/ex1.xlsx")

In [7]:
excel.head()

Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo